### ISSUE TITLE
Image reinstall PiVPN with each restart

### ISSUE THREAD

**Issue by ualex73** [ljishen/pivpn-docker#1]
It seems every container restart reinstalls the PiVPN software ... That seems a bit too much, especially during reboots of a machine. The container should be persistant, the image not ofcourse.

**Comment by alonpeer** [comment]
@ualex73 how did you resolve this issue? How do you persist the container? This seems to happen to me as well.

**Comment by ualex73** [comment]
I didn't solve it with pivpn-docker, but I switched to the following docker image:
kylemanna/openvpn

This works perfectly the last 6 months 👍

**Comment by alonpeer** [comment]
Thanks! Since I'm running on a raspberry pi, which has an ARM architecture, I was able to find `giggio/openvpn-arm`, which is the ARM port of `kylemanna/openvpn`. It works 😄

**Comment by ualex73** [comment]
The giggio/openvpn-arm one seems very old :-(

You can also use the GitHub repo from kylemanna/openvpn and change it from:
FROM alpine:latest
to:
FROM arm64v8/alpine:latest

And then do a docker build, then you should up-to-date.

**Comment by alonpeer** [comment]
Good point. Ended up using a different, more up-to-date port: https://github.com/for-rpi/docker-openvpn
