### ISSUE TITLE
Updating the setupVars.conf file

### ISSUE THREAD

**Issue by alonpeer** [ljishen/pivpn-docker#3]
I'm running a container of this image on LibreELEC with the following command:

`docker run --rm --privileged -p 443:443/udp --name=pivpn -v /storage/ovpns:/home/pivpn/ovpns ljishen/pivpn`

I would like to set a different port and password, but I don't know how to edit the setupVars.conf file, as mentioned in the README.

**Comment by ljishen** [comment]
Sorry that I have no time to keep this repository up to date. But just feel free to create pull requests if you find any problems!
