### ISSUE TITLE
Abandoned project?

### ISSUE THREAD

**Issue by XayOn** [ljishen/pivpn-docker#9]
It seems like this project has been unmantained for three years, forks happened.
https://github.com/xptsp/pivpn-docker

**Comment by ljishen** [comment]
Yes, please forks and keep updating this project on your own. I don't have extra time to maintain it now.

**Comment by XayOn** [comment]
@ljishen You should consider adding a note on the Readme, and/or archive the project ( on your project's settings, danger zone, archive)
